### ISSUE TITLE
`encodeBase16` should encode, not decode

### ISSUE THREAD

**Issue by nfrisby** [emilypi/Base16#15]
This line from the current tip of the `master` branch looks like a typo: encode calls decode. (And my script's calls to `encodeBase16` are misbehaving.) Thanks!

https://github.com/emilypi/Base16/blob/9d6b2c8f74314104f3c47b7d547a68532785ad1c/src/Data/ByteString/Short/Base16.hs#L47

**Comment by emilypi** [comment]
wow strange - that's a very old typo indeed! i'll push out a fix asap

**Comment by andrewthad** [comment]
This fix is on GitHub `master` but is not yet available on Hackage.
