### ISSUE TITLE
Support for GHC 9.4

### ISSUE THREAD

**Issue by Kleidukos** [emilypi/Base16#21]
Thanks again for this library, it's quite reliable and sturdy. 

I would like to extend a library of my own to support GHC 9.4, and it would appear that `base16` is somewhat of a blocker. Could the library be ported to support it? 

Cheers

**Comment by emilypi** [comment]
I'll see what's needed today and have an update

**Comment by emilypi** [comment]
Done - `base16-3.2.1` is now up on Hackage!
