### ISSUE TITLE
Please bump base bound for 0.3.2.1 to < 4.20

### ISSUE THREAD

**Issue by tomjaguarpaw** [emilypi/Base16#31]
Both of these work, so could you please make a Hackage revision to bump the bound for `base` on `base16-0.3.2.1` to `< 4.20`? It's currently at `< 4.18`.

* `cabal repl -b base16==0.3.2.1 -w ghc-9.6 --allow-newer=base16`
* `cabal repl -b base16==0.3.2.1 -w ghc-9.8 --allow-newer=base16`

**Comment by emilypi** [comment]
`base16-1.0` supports `<4.20` though, so there's your motivation to upgrade. I don't subscribe to the policy of "support old versions forever on as many `base` versions as possible". I progress my libraries and test only the GHC's I can reasonably automate and locally support. If you want to maintain that particular version of `base16` longer, you have a remedy: fork.

**Comment by emilypi** [comment]
Closed because I fail to see how twitter callouts are necessary in what I thought was a goodwill line of communication.

**Comment by tomjaguarpaw** [comment]
Sorry if what I said on Twitter sounded rude. That wasn't my intention and I wasn't "calling out". I was intending to share information with an interested party (Moritz).

**Comment by tomjaguarpaw** [comment]
(And you can see I didn't mention you by name or Twitter handle in the discussion, exactly because it wasn't a "call out". I was trying to be helpful to Moritz, that's all.)

**Comment by emilypi** [comment]
You directly linked to this issue with a comment that could be interpreted in context as "i am unsatisfied with this response" (You), which was already in the context of "Emily did something annoying I don't like" (Moritz). Your nitpicks over what constitutes a "callout" are wrong - you're drawing negative public criticism unnecesarily to what is a completely resolvable issue with talking. _That is a callout by definition_.

If you come onto my projects asking me for labor and then _pester_ me about it publicly when I'm trying to address your rationale, you didn't come in requesting labor. You came in demanding it. *That* is where we have a problem.

**Comment by tomjaguarpaw** [comment]
You are welcome to your interpretation of course. The interpretation you describe here does not match my intentions and I regret having caused offence.
